apiVersion: eks.services.k8s.aws/v1alpha1
kind: PodIdentityAssociation
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    app: bucket-lister
  name: bucket-lister
spec:
  clusterRef:
    from:
      namespace: kube-public
      name: cluster
  namespace: default
  roleARN: arn:aws:iam::{{ .Values.aws.accountId }}:role/{{ .Values.projectName }}-bucket-lister
  serviceAccount: bucket-lister
