traefik:
  image:
    pullPolicy: Always

  deployment:
    revisionHistoryLimit: 0

  ingressClass:
    enabled: true
    isDefaultClass: true
    name: ingress

  providers:
    kubernetesCRD:
      enabled: false
    kubernetesIngress:
      enabled: true
      ingressClass: ingress
      publishedService:
        enabled: false

  ports:
    web:
      forwardedHeaders:
        insecure: true
    websecure:
      forwardedHeaders:
        insecure: true

  topologySpreadConstraints:
    - topologyKey: topology.kubernetes.io/zone
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule
      minDomains: 3
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: traefik
    - topologyKey: kubernetes.io/hostname
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: traefik

  logs:
    general:
      format: json
      level: "INFO"
      noColor: true
    access:
      enabled: true
      format:  json

  service:
    enabled: true
    type: ClusterIP

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      memory: 100Mi

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5

  metrics:
    prometheus:
      enabled: true
      addEntryPointsLabels: true
      addServicesLabels: true
