apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/johan-vandeweerd-hs/cluster-playground
    path: applications/platform
    targetRevision: eks-auto
    helm:
      parameters:
        - name: clusterName
          value: {{ .Values.cluster.name }}
  destination:
    server: {{ .Values.cluster.arn }}
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
