apiVersion: v1
kind: Secret
metadata:
  name: cloud-costs
stringData:
  cloud-integration.json: |
    {
      "aws": {
        "athena": [
          {
            "bucket": "{{ .Values.athena.bucket }}",
            "region": "{{ .Values.aws.region }}",
            "workgroup": "{{ .Values.athena.workgroup }}",
            "database": "{{ .Values.athena.database }}",
            "table": "{{ .Values.athena.table }}",
            "account": "{{ .Values.aws.accountId }}",
            "authorizer": {
              "authorizerType": "AWSServiceAccount"
            }
          }
        ]
      }
    }
