---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: open-telemetry
spec:
  provider:
    aws:
      region: {{ .Values.aws.region }}
      role: {{ .Values.roleArn }}
      service: SecretsManager
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-telemetry
spec:
  secretStoreRef:
    kind: SecretStore
    name: open-telemetry
  dataFrom:
    - extract:
        key: {{ .Values.secretsKey }}
  target:
    name: open-telemetry
