apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: open-telemetry-metrics
spec:
  mode: statefulset
  managementState: managed
  serviceAccount: open-telemetry-metrics-collector
  imagePullPolicy: Always
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 512Mi
  autoscaler:
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilization: 50
    targetMemoryUtilization: 60
  topologySpreadConstraints:
    - topologyKey: topology.kubernetes.io/zone
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule
      minDomains: 3
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: open-telemetry-metrics-collector
    - topologyKey: kubernetes.io/hostname
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: open-telemetry-metrics-collector
  targetAllocator:
    enabled: true
  config:
    extensions:
      sigv4auth:
        region: {{ .Values.aws.region }}
        service: aps
    receivers:
      prometheus:
        config:
          global:
            scrape_interval: 30s
            scrape_timeout: 10s
          scrape_configs:
            - job_name: cadvisor
              kubernetes_sd_configs:
                - role: node
              scheme: https
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: true
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              relabel_configs:
                - replacement: kubernetes.default.svc:443
                  target_label: __address__
                - source_labels: [ __meta_kubernetes_node_name ]
                  target_label: __metrics_path__
                  regex: (.+)
                  replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
              metric_relabel_configs:
                - source_labels: [ pod ]
                  regex: ([a-z\-]+)\-[a-z0-9]+(\-[a-z0-9]+)?$
                  replacement: $1
                  target_label: deployment
            - job_name: pods
              honor_labels: true
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - action: keep
                  source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_scrape ]
                  regex: true
                - action: drop
                  source_labels: [ __meta_kubernetes_pod_phase ]
                  regex: Pending|Succeeded|Failed|Completed

                - action: replace
                  source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_scheme ]
                  regex: (https?)
                  target_label: __scheme__
                - action: replace
                  source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_ip ]
                  regex: (\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})
                  replacement: '[$2]:$1'
                  target_label: __address__
                - action: replace
                  source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_ip ]
                  regex: (\d+);((([0-9]+?)(\.|$)){4})
                  replacement: $2:$1
                  target_label: __address__
                - action: replace
                  source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_path ]
                  regex: (.+)
                  target_label: __metrics_path__
    #              metric_relabel_configs:
    #                - action: keep
    #                  source_labels: [ __name__ ]
    #                  regex: my_metric_name_prefix_.*
    processors:
      batch:
        timeout: 30s
      k8sattributes:
        extract:
          metadata:
            - k8s.deployment.name
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
          - sources:
              - from: connection
    exporters:
      prometheusremotewrite:
        auth:
          authenticator: sigv4auth
        endpoint: {{ .Values.prometheus.endpoint }}api/v1/remote_write
        max_batch_size_bytes: 1000000
        resource_to_telemetry_conversion:
          enabled: true
    service:
      telemetry:
        logs:
          level: info
      extensions:
        - sigv4auth
      pipelines:
        metrics:
          receivers:
            - prometheus
          processors:
            - k8sattributes
            - batch
          exporters:
            - prometheusremotewrite