apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-telemetry-metrics
rules:
  - apiGroups: [""]
    resources: ["nodes", "namespaces", "services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
  # cadvisor
  - apiGroups: [""]
    resources: ["nodes/proxy"]
    verbs: ["get"]
  - nonResourceURLs: ["/metrics/cadvisor"]
    verbs: ["get"]
